# Use specific Node.js version (16) that's likely available in most GitLab environments
image: node:16-alpine

cache:
  paths:
    - node_modules/
  key: ${CI_COMMIT_REF_SLUG}

stages:
  - build
  - deploy

build:
  stage: build
  script:
    # Install necessary packages for alpine-based image
    - apk add --no-cache git
    - npm ci
    - npm run build
  artifacts:
    paths:
      - build/

pages:
  stage: deploy
  script:
    - mkdir -p public
    - cp -r build/* public/
    # Add a small info file about deployment
    - echo "Tier List of Problems - Deployed for cgrey on $(date)" > public/deployment-info.txt
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  # Site will be deployed to https://cgrey.gitlab.io/tier-list-of-problems/
